# Numpy

In [3]:
import numpy as np

# Creaing Arrays

In [6]:
mylist = [1,2,3]
x = np.array(mylist)
x

array([1, 2, 3])

In [7]:
y = np.array([4,5,6])
y

array([4, 5, 6])

In [8]:
m = np.array([[7, 8, 9], [10, 11, 12]])
m

array([[ 7,  8,  9],
       [10, 11, 12]])

In [9]:
m.shape

(2, 3)

In [12]:
n = np.arange(0,30, 2)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [14]:
o = np.linspace(0, 4, 9)
o

array([ 0. ,  0.5,  1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ])

In [15]:
o.resize(3, 3)
o

array([[ 0. ,  0.5,  1. ],
       [ 1.5,  2. ,  2.5],
       [ 3. ,  3.5,  4. ]])

In [18]:
np.ones((2, 3))

array([[ 1.,  1.,  1.],
       [ 1.,  1.,  1.]])

In [19]:
np.zeros((2, 3))

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

In [20]:
np.eye(3)

array([[ 1.,  0.,  0.],
       [ 0.,  1.,  0.],
       [ 0.,  0.,  1.]])

In [21]:
np.diag(y)

array([[4, 0, 0],
       [0, 5, 0],
       [0, 0, 6]])

In [25]:
np.array([1, 2, 3] * 3)

array([1, 2, 3, 1, 2, 3, 1, 2, 3])

In [26]:
np.repeat([1, 2, 3], 3)

array([1, 1, 1, 2, 2, 2, 3, 3, 3])

In [27]:
p = np.ones([2,3], int)
p

array([[1, 1, 1],
       [1, 1, 1]])

In [30]:
np.vstack([p, 2 * p, p * 30])

array([[ 1,  1,  1],
       [ 1,  1,  1],
       [ 2,  2,  2],
       [ 2,  2,  2],
       [30, 30, 30],
       [30, 30, 30]])

In [34]:
np.hstack([p, 2 * p, p * 30 + 1])

array([[ 1,  1,  1,  2,  2,  2, 31, 31, 31],
       [ 1,  1,  1,  2,  2,  2, 31, 31, 31]])

# Operations

In [35]:
x + y

array([5, 7, 9])

In [36]:
x * y

array([ 4, 10, 18])

In [37]:
x** 2

array([1, 4, 9])

In [38]:
x ** 5

array([  1,  32, 243])

In [39]:
x.dot(y)

32

In [41]:
z = np.array([y, y**2])
z

array([[ 4,  5,  6],
       [16, 25, 36]])

In [42]:
z.shape

(2, 3)

In [43]:
z.T

array([[ 4, 16],
       [ 5, 25],
       [ 6, 36]])

In [44]:
z.T.shape

(3, 2)

In [45]:
z.dtype

dtype('int64')

In [47]:
z = z.astype('f')
z.dtype

dtype('float32')

In [48]:
a = np.array([-4, -2, 1,3,5])

In [49]:
a.sum()

3

In [50]:
a.max()

3.2619012860600183

In [51]:
a.min()

-4

In [52]:
a.mean()

0.59999999999999998

In [53]:
a.std()

3.2619012860600183

In [54]:
a.argmax()

4

In [55]:
a.argmin()

0

# Indexing / Slicing

In [56]:
s = np.arange(13) ** 2
s

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144])

In [57]:
s[0], s[4], s[0: 3]

(0, 16, array([0, 1, 4]))

In [58]:
a[1: 5]

array([-2,  1,  3,  5])

In [59]:
a[-4:]

array([-2,  1,  3,  5])

In [60]:
s[-5::-2]

array([64, 36, 16,  4,  0])

In [62]:
r = np.arange(36)
r.resize((6,6))
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 31, 32, 33, 34, 35]])

In [73]:
r[2,5]

17

In [76]:
r[3, 0:3]

array([18, 19, 20])

In [78]:
r[:2, :-1]

array([[ 0,  1,  2,  3,  4],
       [ 6,  7,  8,  9, 10]])

In [82]:
r[-1, ::-3]

array([35, 32])

In [83]:
r[r > 30]

array([31, 32, 33, 34, 35])

In [85]:
r[r > 30] = 30
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [86]:
r

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [88]:
r2 = r[:3, :3]
r2

array([[ 0,  1,  2],
       [ 6,  7,  8],
       [12, 13, 14]])

In [90]:
r2[:] = 0
r2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [91]:
r

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [92]:
r_rcopy = r.copy()
r_rcopy

array([[ 0,  0,  0,  3,  4,  5],
       [ 0,  0,  0,  9, 10, 11],
       [ 0,  0,  0, 15, 16, 17],
       [18, 19, 20, 21, 22, 23],
       [24, 25, 26, 27, 28, 29],
       [30, 30, 30, 30, 30, 30]])

In [94]:
r_rcopy[:] = 10
print(r_rcopy)
print()
print(r)

[[10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]
 [10 10 10 10 10 10]]

[[ 0  0  0  3  4  5]
 [ 0  0  0  9 10 11]
 [ 0  0  0 15 16 17]
 [18 19 20 21 22 23]
 [24 25 26 27 28 29]
 [30 30 30 30 30 30]]


# Iterating Over Arrays

In [96]:
test = np.random.randint(0, 10, (4,3))
test

array([[2, 1, 1],
       [5, 0, 0],
       [6, 1, 0],
       [9, 6, 5]])

In [97]:
for row in test:
    print(row)

[2 1 1]
[5 0 0]
[6 1 0]
[9 6 5]


In [100]:
for i in range(len(test)):
    print(test[i])

[2 1 1]
[5 0 0]
[6 1 0]
[9 6 5]


In [101]:
for i, row in enumerate(test):
    print('row', i, 'is', row)

row 0 is [2 1 1]
row 1 is [5 0 0]
row 2 is [6 1 0]
row 3 is [9 6 5]


In [102]:
test2 = test ** 2
test2

array([[ 4,  1,  1],
       [25,  0,  0],
       [36,  1,  0],
       [81, 36, 25]])

In [103]:
for i, j in zip(test, test2):
    print(i, '+', j, '=', i + j)

[2 1 1] + [4 1 1] = [6 2 2]
[5 0 0] + [25  0  0] = [30  0  0]
[6 1 0] + [36  1  0] = [42  2  0]
[9 6 5] + [81 36 25] = [90 42 30]
